### ISSUE TITLE
Add a customizable comment section on exported files

### ISSUE THREAD

**Issue by AlisCode** [impero-com/typebinder#17]
Generated files should have a note saying "This was generated by `typebinder` version x.y".

Auto-generated bindings shouldn't be modified by hand. A warning is the most we can do in that case.

**Comment by AlisCode** [comment]
For guidance if anyone wants to try to solve this : 

* We need to add `Comments` support in `ts_json_subset`. This will also be useful when/if we want to support copying Rust struct / enums / alias documentation to TypeScript.
* A quick & easy fix can be to add a comment to the list of statements in `typebinder/src/exporters/file_exporter.rs`.  
* We can also add a `CommentStatement` variant ... 
* Any other (potentially) cleaner solution is welcome :)

**Comment by greyblake** [comment]
* Consider adding a link to original Rust source file
