### ISSUE TITLE
Macro solving errors are not handled properly 

### ISSUE THREAD

**Issue by AlisCode** [impero-com/typebinder#18]
If a macro solver doesn't solve properly, the process doesn't generate the file without printing an error. 

Macro solving should be handled the same way as type solving.

**Comment by greyblake** [comment]
Address in the main code base by adjusting a custom macro solver.
Closing the issue.

**Comment by AlisCode** [comment]
It seems there was a misunderstanding when this issue was first filed, the error is displayed indeed. The `typebinder` process (CLI) should probably be killed when such an error occurs.

**Comment by AlisCode** [comment]
Closing the issue now, this was indeed a bug in our integration codebase
