### ISSUE TITLE
Add `extend string` to generic types used in object key position

### ISSUE THREAD

**Issue by gobanos** [impero-com/typebinder#25]
The following Rust struct

```rust
#[derive(Serialize, Deserialize)]
pub struct Foo<Key, Value>
where
    Key: Eq + Ord,
{
    pub foos: BTreeMap<Key, Value>,
}
```
is translated to this invalid typescript : 
```typescript
export interface Foo<Key, Value> {
    foos: Record<Key, Value> // <- Type 'Key' does not satisfy the constraint 'string | number | symbol'.
}
```
The expected typescript is : 
```typescript
export interface Foo<Key extends string, Value> {
    foos: Record<Key, Value>
}
```

**Comment by AlisCode** [comment]
So : 
* We need to change the Map exporter
* We need to support `extends OtherType` in `ts_json_subset`
* We need to provide a way to apply a constraint on generics (such as `extends OtherType`). This means that : 
    * Generics must be mutable
    * Generics can no longer be `syn`'s `Generics` type, as we need to store the constraint in there somehow
